### ISSUE TITLE
菜单地址默认跳转到 localhost

### ISSUE THREAD

**Issue by yuanzhixiang** [halo-dev/halo#2898] opened 2022-12-08 20:18 UTC
### 是什么版本出现了此问题？

2.0.1

### 使用的什么数据库？

MySQL 8.x

### 使用的哪种方式部署？

Docker

### 发生了什么？

默认的菜单地址显示 `http://localhost:8090/about`，期望为 `/about`，但系统中找不到修改该地址的地方

<img width="1515" alt="image" src="https://user-images.githubusercontent.com/25138766/206559011-c4c1619f-f9b6-4145-b12c-6220ff265895.png">

**Comment by JohnNiang** [comment] 2022-12-09 02:03
Please refer to <https://github.com/halo-dev/halo/issues/2818#issuecomment-1337657672>.

**Comment by JohnNiang** [comment] 2022-12-09 02:14
This issue is a duplicate of issue <https://github.com/halo-dev/halo/issues/2818>, so I'm going to close it. Please feel free to reopen if I'm wrong.

/triage duplicate
/close

**Closed by JohnNiang** 2022-12-09 02:14 UTC
Labels: triage/duplicate
