### ISSUE TITLE
登录时警告密码错误

### ISSUE THREAD

**Issue by S1noFGrEEd** [halo-dev/halo#5553] opened 2024-03-21 12:19 UTC
### 系统信息

- 外部访问地址: https://demo.halo.run
- 启动时间: 2024-03-21 19:56
- 版本: 2.13.1
- 构建时间: 2024-03-06 17:40
- Git Commit: 9473261
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Linux / 5.15.0-88-generic
- 已激活主题: [Earth](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
  - [Metrics Graph](https://github.com/guqing/plugin-metrics-graph)
  - [Vditor编辑器](https://github.com/justice2001/veditor-plugin)
  - [文本绘图](https://github.com/halo-sigs/plugin-text-diagram)
  - [Docsme](https://github.com/f2ccloud/plugin-docsme)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - 联系表单
  - [文章限制阅读 Pro](https://github.com/f2ccloud/plugin-restricted-reading-pro)
  - [应用市场](https://github.com/halo-dev/plugin-app-store)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [站点迁移](https://github.com/halo-sigs/plugin-migrate)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [RSS](https://github.com/halo-dev/plugin-feed)
  - [StackEdit](https://github.com/halo-sigs/plugin-stackedit)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [Unsplash](https://github.com/halo-sigs/plugin-unsplash)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Umami](https://github.com/halo-sigs/plugin-umami)

### 使用的哪种方式运行？

Docker

### 发生了什么？

![1](https://github.com/halo-dev/halo/assets/143989912/f36f0683-3ab9-4950-b805-af852913fae2)
![2](https://github.com/halo-dev/halo/assets/143989912/9d39b6cf-87f9-4f20-97b8-a7a3937becaf)
登录填写了设置的密码却显示用户名或密码错误，并且直接将密码栏清空无法登录，然后重新注册的时候发送了验证码但是邮箱没有收到，或者显示请求上限，密码输入的是正确的密码，甚至有重新设置密码，但是依旧无法登录

### 附加信息

视频一直上传失败。。。

**Comment by ruibaby** [comment] 2024-03-22 02:25
Duplicate of https://github.com/halo-dev/halo/discussions/5563

/triage unresolved
/close

**Closed by ruibaby** 2024-03-22 02:25 UTC
Labels: triage/unresolved
